name: everydayTask

on:
  workflow_dispatch:
  push:
  schedule:
  # 设置循环部署的时间段
    - cron: '*/10 * * * *'
    - cron: '0 15 * * *'

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: get-test
        run: |
          git config --global user.email "zhangxianzhuo@hotmail.com"
          git config --global user.name "zhangxianzhuo"
          git pull
          date > file.txt
          git add file.txt
          git commit -m "today's file"
          git push
