name: everydayTask

on:
  schedule:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: stepOne
        run: |
          num=$(date -d 'today' +%-j)
          if [ $((${num} % 130)) -ne 0 ]
          then
            q=$(sed -n "${num}p" askAnswer.csv | awk -F~ '{print $1}' | awk -F, '{print $1": "$2}' | sed 's/\"//g')
            a=$(sed -n "${num}p" askAnswer.csv | awk -F~ '{print $2}' | awk -F, '{print $1": "$2}' | sed 's/\"//g')
          else
            q="恭喜你"
            a="完成了一遍"
          fi
          cat template.html | sed -e "13c ${q}" | sed -e "16c ${a}" >index.html
      - name: deploy
        run: |
          git config user.email "zhangxianzhuo@hotmail.com"
          git config user.name "zhangxianzhuo"
          git pull
          git add .
          git commit -m "everyday update content"
          git push
